name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - mathcomp/mathcomp:2.2.0-coq-8.19
      max-parallel: 4
      # don't cancel all in-progress jobs if one matrix job fails:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'clutch.opam'
          custom_image: ${{ matrix.image }}
          install : |
            startGroup "Install dependencies"
              sudo apt-get update -y -q
              opam repo remove coq-released
              opam repo add rocq-released https://rocq-prover.org/opam/released
              opam repo add iris-dev https://gitlab.mpi-sws.org/iris/opam.git
              opam pin add -n -y -k path $PACKAGE $WORKDIR
              opam update -y
              opam reinstall --forget-pending --yes
              opam install --confirm-level=unsafe-yes -j 2 $PACKAGE --deps-only
            endGroup
          before_script: |
            sudo chown -R coq:coq . # workaround a permission issue
          script: |
            startGroup Clone coqdocjs
              git clone https://github.com/ahuoguo/coqdocjs.git
            endGroup
            startGroup Build
              make -j2
            endGroup
            startGroup HTML Build
              make -f Makefile.ci -j2
            endGroup
          uninstall: |
            make clean
      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .
      - name: Upload html as artifact
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
          path: html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
